#!/bin/bash
# M114: update touchoff from variables.txt

VARS_FILE="/home/cnc/linuxcnc/configs/xzacw/variables.txt"
touchoff=$(grep "^touchoff=" "$VARS_FILE" | cut -d '=' -f 2)

pipe="/home/cnc/linuxcnc/configs/xzacw/variables_pipe.json"

# read existing pipe
if [ -f "$pipe" ]; then
  data=$(cat "$pipe")
else
  data="{}"
fi

# update value
echo "$data" | python3 -c "import sys,json; d=json.load(sys.stdin); d['touchoff']=$touchoff; print(json.dumps(d))" > "$pipe"
exit 0
